In [1]:
#Import top50.csv file
import pandas as pd
top50_df = pd.read_csv("top50.csv", encoding='latin-1')
top50_df.head()

Unnamed: 0                       Track.Name    Artist.Name           Genre  \
0           1                         Señorita   Shawn Mendes    canadian pop   
1           2                            China       Anuel AA  reggaeton flow   
2           3    boyfriend (with Social House)  Ariana Grande       dance pop   
3           4  Beautiful People (feat. Khalid)     Ed Sheeran             pop   
4           5      Goodbyes (Feat. Young Thug)    Post Malone         dfw rap   

   Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.  \
0               117      55            76              -6         8        75   
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  Popularity  
0      191               4             3          79  
1      302               8             9          92  
2      186              12            46          85  
3      198              12            19          86  
4      175              45             7          94

In [2]:
import numpy as np
from pathlib import Path
from collections import Counter

In [3]:
#Remove uneccessary columns
top50_df.drop(['Unnamed: 0', 'Track.Name', 'Artist.Name'],  inplace=True, axis=1)
top50_df.head()

Genre  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
0    canadian pop               117      55            76              -6   
1  reggaeton flow               105      81            79              -4   
2       dance pop               190      80            40              -4   
3             pop                93      65            64              -8   
4         dfw rap               150      65            58              -4   

   Liveness  Valence.  Length.  Acousticness..  Speechiness.  Popularity  
0         8        75      191               4             3          79  
1         8        61      302               8             9          92  
2        16        70      186              12            46          85  
3         8        55      198              12            19          86  
4        11        18      175              45             7          94

In [4]:
#Get the dummies and store it in a variable
dummies = pd.get_dummies(top50_df.Genre)
#Concatenate the dummies to the original dataframe
top50final_df = pd.concat([top50_df, dummies], axis='columns')
#Drop the values
top50final_df.drop(['Genre'], inplace=True, axis='columns')
#Print new dataframe
top50final_df.head()

Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.  \
0               117      55            76              -6         8        75   
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  Popularity  ...  electropop  \
0      191               4             3          79  ...           0   
1      302               8             9          92  ...           0   
2      186              12            46          85  ...           0   
3      198              12            19          86  ...           0   
4      175              45             7          94  ...           0   

   escape room  latin  panamanian pop  pop  pop house  r&b en espanol  \
0            0      0               0    0          0               0   
1            0      0               0    0          0               0   
2            0      0               0    0          0               0   
3            0      0               0    1          0               0   
4            0      0               0    0          0               0   

   reggaeton  reggaeton flow  trap music  
0          0               0           0  
1          0               1           0  
2          0               0           0  
3          0               0           0  
4          0               0           0  

[5 rows x 31 columns]

In [5]:
#Seperating Popular songs to >90 (Y) and <=89 (N (less popular))    
top50final_df['Pop Y/N'] = pd.Series(np.where(top50final_df.Popularity.values <= 89, 0, 1), top50final_df.index)
top50final_df.head()

Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.  \
0               117      55            76              -6         8        75   
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  Popularity  ...  escape room  latin  \
0      191               4             3          79  ...            0      0   
1      302               8             9          92  ...            0      0   
2      186              12            46          85  ...            0      0   
3      198              12            19          86  ...            0      0   
4      175              45             7          94  ...            0      0   

   panamanian pop  pop  pop house  r&b en espanol  reggaeton  reggaeton flow  \
0               0    0          0               0          0               0   
1               0    0          0               0          0               1   
2               0    0          0               0          0               0   
3               0    1          0               0          0               0   
4               0    0          0               0          0               0   

   trap music  Pop Y/N  
0           0        0  
1           0        1  
2           0        0  
3           0        0  
4           0        1  

[5 rows x 32 columns]

In [6]:
#Drop 'Popularity' Column
top50final_df.drop("Popularity", axis=1, inplace=True)
top50final_df.head()

Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.  \
0               117      55            76              -6         8        75   
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  atl hip hop  ...  escape room  \
0      191               4             3            0  ...            0   
1      302               8             9            0  ...            0   
2      186              12            46            0  ...            0   
3      198              12            19            0  ...            0   
4      175              45             7            0  ...            0   

   latin  panamanian pop  pop  pop house  r&b en espanol  reggaeton  \
0      0               0    0          0               0          0   
1      0               0    0          0               0          0   
2      0               0    0          0               0          0   
3      0               0    1          0               0          0   
4      0               0    0          0               0          0   

   reggaeton flow  trap music  Pop Y/N  
0               0           0        0  
1               1           0        1  
2               0           0        0  
3               0           0        0  
4               0           0        1  

[5 rows x 31 columns]

In [9]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

X = top50final_df.drop("Pop Y/N", axis=1)

y = top50final_df["Pop Y/N"]

X_scaled = StandardScaler().fit_transform(X)

X_scaled

array([[-0.10003973, -0.64306057,  0.3911946 , ..., -0.20412415,
        -0.20412415, -0.14285714],
       [-0.4923524 ,  1.20236711,  0.64521708, ..., -0.20412415,
         4.89897949, -0.14285714],
       [ 2.28652901,  1.13138912, -2.65707504, ..., -0.20412415,
        -0.20412415, -0.14285714],
       ...,
       [-0.65581601,  1.06041114, -0.20152449, ..., -0.20412415,
        -0.20412415, -0.14285714],
       [-0.52504512,  0.42160925, -1.04826606, ..., -0.20412415,
        -0.20412415, -0.14285714],
       [-0.81927962,  1.06041114,  0.30652045, ..., -0.20412415,
        -0.20412415, -0.14285714]])

In [8]:
#balance of 'Pop Y/N' values
y.value_counts()

0    34
1    16
Name: Pop Y/N, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, random_state=1)

# Naive Random Oversampling

In [11]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state = 1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

#View the Count
Counter(y_resampled)


Counter({1: 22, 0: 22})

In [12]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver="lbfgs", random_state =1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [13]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)

from sklearn.metrics import balanced_accuracy_score
print(balanced_accuracy_score(y_test, y_pred))

0.25


In [14]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[6, 6],
       [1, 0]], dtype=int64)

In [15]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.86      0.50      0.00      0.63      0.00      0.00        12
          1       0.00      0.00      0.50      0.00      0.00      0.00         1

avg / total       0.79      0.46      0.04      0.58      0.00      0.00        13



# SMOTE Oversampling

In [16]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({1: 22, 0: 22})

In [17]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [18]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.2916666666666667

In [19]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[7, 5],
       [1, 0]], dtype=int64)

In [20]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.88      0.58      0.00      0.70      0.00      0.00        12
          1       0.00      0.00      0.58      0.00      0.00      0.00         1

avg / total       0.81      0.54      0.04      0.65      0.00      0.00        13



# Undersampling

In [21]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 15, 1: 15})

In [22]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [23]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.2916666666666667

In [24]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[7, 5],
       [1, 0]], dtype=int64)

In [25]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.88      0.58      0.00      0.70      0.00      0.00        12
          1       0.00      0.00      0.58      0.00      0.00      0.00         1

avg / total       0.81      0.54      0.04      0.65      0.00      0.00        13



# Combination (Over and Under) Sampling

In [26]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=1)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({0: 12, 1: 19})

In [27]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

C:\Users\mleegan\Anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=1)

In [28]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.75

In [29]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[6, 6],
       [0, 1]], dtype=int64)

In [30]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.50      1.00      0.67      0.71      0.48        12
          1       0.14      1.00      0.50      0.25      0.71      0.53         1

avg / total       0.93      0.54      0.96      0.63      0.71      0.48        13



# Balanced Random Forest Classifier

In [31]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

rf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=1) 
rf_model.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [32]:
# Calculated the balanced accuracy score
y_pred = rf_model.predict(X_test)
print(balanced_accuracy_score(y_test, y_pred))

0.7916666666666667


In [33]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[7, 5],
       [0, 1]], dtype=int64)

In [34]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.58      1.00      0.74      0.76      0.56        12
          1       0.17      1.00      0.58      0.29      0.76      0.61         1

avg / total       0.94      0.62      0.97      0.70      0.76      0.56        13



In [35]:
# List the features sorted in descending order by feature importance
feature_names = X.columns
sorted(zip(rf_model.feature_importances_, feature_names), reverse=True)

[(0.14420696562846638, 'Liveness'),
 (0.12514017047478196, 'Beats.Per.Minute'),
 (0.11091382512268234, 'Danceability'),
 (0.09885192459129948, 'Valence.'),
 (0.09299665062844344, 'Acousticness..'),
 (0.08952222490207237, 'Length.'),
 (0.08090617731448059, 'Energy'),
 (0.06666410515968542, 'Speechiness.'),
 (0.05506879811954927, 'Loudness..dB..'),
 (0.02689196049608101, 'pop'),
 (0.022419045405513434, 'dfw rap'),
 (0.02209508273361922, 'latin'),
 (0.01343753685790676, 'dance pop'),
 (0.008991144272394273, 'brostep'),
 (0.007741290854877809, 'canadian pop'),
 (0.006754348485192141, 'panamanian pop'),
 (0.004549762375532645, 'canadian hip hop'),
 (0.004198153475017511, 'electropop'),
 (0.003016037772867768, 'reggaeton'),
 (0.002754011086272116, 'country rap'),
 (0.00270660800552105, 'escape room'),
 (0.002360056975188554, 'reggaeton flow'),
 (0.0020742512847776004, 'pop house'),
 (0.0020058880859796183, 'edm'),
 (0.001970412141464775, 'atl hip hop'),
 (0.0016578628615393318, 'r&b en espan

# Easy Ensemble AdaBoost Classifier

In [36]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators = 100, random_state = 1)
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [37]:
# Calculated the balanced accuracy score
y_pred = eec.predict(X_test)
print(balanced_accuracy_score(y_test, y_pred))

0.7916666666666667


In [38]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[7, 5],
       [0, 1]], dtype=int64)

In [39]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.58      1.00      0.74      0.76      0.56        12
          1       0.17      1.00      0.58      0.29      0.76      0.61         1

avg / total       0.94      0.62      0.97      0.70      0.76      0.56        13

